# Generated by Django 5.2.8 on 2025-11-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='rollNo',
            new_name='roll_No',
        ),
    ]
