# Generated by Django 5.2.8 on 2025-11-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_rollno_student_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
