# Generated by Django 5.2.8 on 2025-11-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emloyee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
