# Generated by Django 5.2.8 on 2025-11-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_emloyee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emloyee',
            old_name='weight',
            new_name='age',
        ),
    ]
