# Generated by Django 5.2.8 on 2025-11-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_category_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='user/'),
        ),
    ]
